# Generated by Django 5.0.1 on 2024-02-06 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userbase",
            options={"verbose_name": "Accounts", "verbose_name_plural": "Accounts"},
        ),
        migrations.AddField(
            model_name="userbase",
            name="first_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
