# Generated by Django 5.0.1 on 2024-02-06 11:54

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_userbase_options_remove_userbase_first_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbase",
            name="country",
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
