# Generated by Django 5.0.1 on 2024-02-06 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_userbase_country"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userbase",
            name="country",
        ),
    ]
